# Generated by Django 3.0.4 on 2020-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_sensor', models.IntegerField()),
                ('Estado_sensor', models.CharField(max_length=100)),
                ('Municipio_sensor', models.CharField(max_length=100)),
                ('Bairro_sensor', models.CharField(max_length=100)),
                ('Deteccao_sensor', models.BooleanField()),
                ('DataHora_sensor', models.DateTimeField()),
            ],
        ),
    ]
